Message 1:
Process exited with status 1: Traceback (most recent call last):
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/house_prices/data_cleaning/data_cleaning_run_code.py", line 129, in <module>
    generated_code_function()
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/house_prices/data_cleaning/data_cleaning_run_code.py", line 51, in generated_code_function
    test_df = convert_data_types(test_df, numerical_columns, target_type='float')
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/tools/ml_tools.py", line 213, in convert_data_types
    raise ValueError(f"Column '{column}' not found in the DataFrame.")
ValueError: Column 'SalePrice' not found in the DataFrame.



Message 2:
Process exited with status 1: Traceback (most recent call last):
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/house_prices/data_cleaning/data_cleaning_run_code.py", line 75, in <module>
    generated_code_function()
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/competition/house_prices/data_cleaning/data_cleaning_run_code.py", line 58, in generated_code_function
    test_df = convert_data_types(test_df, categorical_columns, target_type='str')
  File "/mnt/d/PythonProjects/AutoKaggleMaster/multi_agents/tools/ml_tools.py", line 213, in convert_data_types
    raise ValueError(f"Column '{column}' not found in the DataFrame.")
ValueError: Column 'FireplaceQu' not found in the DataFrame.



